# This file adds type hints for ROOT classes used in the ExponentialMixtures package. It is not a complete typing of ROOT, but only includes the classes and methods that are used in the package to satisfy pylance.
from typing import Any


class _RootObject:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def __getattr__(self, name: str) -> Any: ...


class RooAbsArg(_RootObject): ...


class RooAbsReal(RooAbsArg):
    def getVal(self, *args: Any, **kwargs: Any) -> float: ...


class RooAbsPdf(RooAbsReal):
    def fitTo(self, data: Any, *args: Any, **kwargs: Any) -> Any: ...

    def generate(self, variables: Any, *args: Any, **kwargs: Any) -> Any: ...


class RooRealVar(RooAbsReal):
    def __init__(self, name: str, title: str, value: float, *args: Any) -> None: ...

    def getVal(self, *args: Any, **kwargs: Any) -> float: ...

    def setVal(self, value: float) -> None: ...


class RooArgList(_RootObject): ...


class RooArgSet(_RootObject): ...


class RooDataHist(_RootObject): ...


class RooDataSet(_RootObject): ...


class RooChi2Var(RooAbsReal): ...


class RooFormulaVar(RooAbsReal): ...


class RooExponential(RooAbsPdf): ...


class RooGenericPdf(RooAbsPdf): ...


class RooAddPdf(RooAbsPdf): ...


class RooGaussian(RooAbsPdf): ...


class RooWorkspace(_RootObject): ...


class RooBinning(_RootObject): ...


class RooRandom:
    @staticmethod
    def randomGenerator() -> Any: ...


class _RooFit:
    def DrawOption(self, *args: Any, **kwargs: Any) -> Any: ...

    def IntegrateBins(self, *args: Any, **kwargs: Any) -> Any: ...

    def LineColor(self, *args: Any, **kwargs: Any) -> Any: ...

    def LineStyle(self, *args: Any, **kwargs: Any) -> Any: ...

    def LineWidth(self, *args: Any, **kwargs: Any) -> Any: ...

    def MarkerSize(self, *args: Any, **kwargs: Any) -> Any: ...

    def Name(self, *args: Any, **kwargs: Any) -> Any: ...

    def Offset(self, *args: Any, **kwargs: Any) -> Any: ...

    def Precision(self, *args: Any, **kwargs: Any) -> Any: ...

    def PrintLevel(self, *args: Any, **kwargs: Any) -> Any: ...

    def Range(self, *args: Any, **kwargs: Any) -> Any: ...

    def RecoverFromUndefinedRegions(self, *args: Any, **kwargs: Any) -> Any: ...

    def Save(self, *args: Any, **kwargs: Any) -> Any: ...

    def Strategy(self, *args: Any, **kwargs: Any) -> Any: ...

    def __getattr__(self, name: str) -> Any: ...


RooFit: _RooFit


def __getattr__(name: str) -> Any: ...